# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    #Encode les mots de passes de l'application (users)
    encoders:
        OC\UserBundle\Entity\User: sha512

    #Définit les différents ROLE de l'app. hiérarchie des rôles
    role_hierarchy:
        #Admin hérité de Auteur - Moderateur
        ROLE_ADMIN: [ ROLE_AUTHOR, ROLE_MODERATOR, ROLE_USER ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    #Il est le fournisseurs de users. les firewalls s'adressent aux providers pour récupérer les users et les identifier
    providers:
        #Nom du provider (arbitraire)  bien utiliser le même dans la config ParFeu
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        #Nom du pare-feu (aléatoire)
        main:
            #masque d'URL. Cela signifie que toutes les URL commençant par « / » sont protégées
            pattern: ^/
            #user_checker: fos_user.user_checker
            anonymous: true
            provider: fos_userbundle
            form_login:
              login_path: fos_user_security_login
              check_path: fos_user_security_check
            logout:
              path:    fos_user_security_logout
              target:  /platform
            remember_me:
                secret: %secret%

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

