<?php

namespace OC\PlatformBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @param $pattern
	 * @return \Doctrine\ORM\QueryBuilder
	 * retourne un QueryBuilder, et non une
	 * Query ou les résultats d'une requête
	 */
	public function getLikeQueryBuilder($pattern)
	{
		return $this
			->createQueryBuilder('c')
			->where('c.name LIKE :pattern')
			->setParameter('pattern', $pattern);
	}
}
